[project]
name = "wonyo-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "matplotlib>=3.11.2",
    "onnx>=1.23.0",
    "onnxruntime>=1.30.0",
    "pandas>=3.0.6",
    "pg8000>=1.31.5",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "tqdm>=4.70.1",
    "typesafe-sdk>=0.7.1",
    "uvicorn>=0.53.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
